# See: https://hibernate.org/orm/
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/playerdb
hibernate.connection.username=postgres
hibernate.connection.password=postgres

# See: https://github.com/brettwooldridge/HikariCP
hibernate.hikari.minimumIdle=5
hibernate.hikari.maximumPoolSize=20
hibernate.hikari.idleTimeout=30000
hibernate.hikari.maxLifetime=2000000
hibernate.hikari.connectionTimeout=30000